version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/client/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/server/"
    schedule:
      interval: "daily"
