repos:
  - repo: "https://github.com/ambv/black"
    rev: "stable"
    hooks:
    - id: "black"
      language_version: "python3.7"
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v2.3.0"
    hooks:
    - id: "flake8"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: 'v0.770'
    hooks:
    - id: "mypy"
      name: "mypy (client/certgrinder)"
      args: ["--strict"]
      files: ^client/
    - id: "mypy"
      name: "mypy (server/certgrinderd)"
      args: ["--strict"]
      files: ^server/
  - repo: "https://github.com/pre-commit/mirrors-isort"
    rev: "v4.3.21"
    hooks:
    - id: "isort"
  - repo: "https://github.com/pycqa/pydocstyle"
    rev: "5.0.2"
    hooks:
    - id: "pydocstyle"
