repos:
  - repo: "https://github.com/ambv/black"
    rev: "22.10.0"
    hooks:
    - id: "black"
      language_version: "python3.9"
  - repo: "https://github.com/pycqa/flake8"
    rev: "5.0.4"
    hooks:
    - id: "flake8"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: 'v0.991'
    hooks:
    - id: "mypy"
      additional_dependencies: ["types-cryptography", "types-requests", "types-PyYAML"]
      name: "mypy (client/certgrinder)"
      args: ["--strict"]
      files: ^client/
    - id: "mypy"
      additional_dependencies: ["types-cryptography", "types-requests", "types-PyYAML"]
      name: "mypy (server/certgrinderd)"
      args: ["--strict"]
      files: ^server/
  - repo: "https://github.com/pre-commit/mirrors-isort"
    rev: "v5.10.1"
    hooks:
    - id: "isort"
  - repo: "https://github.com/pycqa/pydocstyle"
    rev: "6.1.1"
    hooks:
    - id: "pydocstyle"
  - repo: "local"
    hooks:
      - id: "sphinx-build-manpages"
        name: "sphinx manpage build"
        entry: "make --directory docs/ man"
        language: "system"
        pass_filenames: False
      - id: "sphinx-copy-certgrinder-manpage"
        name: "sphinx certgrinder.8 manpage copy"
        entry: "cp docs/_build/man/certgrinder.8 client/man/"
        language: "system"
        pass_filenames: False
      - id: "sphinx-copy-certgrinderd-manpage"
        name: "sphinx certgrinderd.8 manpage copy"
        entry: "cp docs/_build/man/certgrinderd.8 server/man/"
        language: "system"
        pass_filenames: False
      - id: "sphinx-git-add-manpages"
        name: "sphinx manpage git add"
        entry: "git add client/man server/man"
        language: "system"
        pass_filenames: False
