sudo: false
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get -y install git
install:
  - pip install tox-travis
  - pip install codecov
  - pip install pytest-cov
script: tox
after_success:
  - codecov
