---
name: "Certgrinder CI Tests"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
      - name: "Setup Go"
        uses: "actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491"
        with:
          go-version: "1.22.2"
      - name: "Setup Python"
        uses: "actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d"
        with:
          python-version: ${{ matrix.python }}
      - name: "Install Tox and codecov"
        run: "pip install tox codecov"
      - name: "Run Tox"
        run: "tox -e py"
      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@7afa10ed9b269c561c2336fd862446844e0cbf71"
        with:
         fail_ci_if_error: true
...
