name: "Spell checking"
on: ["push"]

jobs:
  check-spelling:
    name: "Spell checking"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "check-spelling/check-spelling@prerelease"
